name: Run Tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default: smoke
        type: choice
        options:
          - smoke_tests
          - with_errors

jobs:
  test:
    name: Run Pytest
    runs-on: ubuntu-latest

#    container:
#      image: python:3.11-slim

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: smoke_tests
        if: "github.event.inputs.deployment_target == 'smoke_tests' "
        run: pytest -m "smoke"

      - name: with_errors
        if: "github.event.inputs.deployment_target == 'with_errors' "
        run: pytest -m "with_error"